# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21dd923117ee1ed9e586fa563b1a5e7ed6e6ec05a284a68adade84d9ab72f67cf3cb8e200b9f988479c4203aaaf8c16aa4f6d5d7516cb4633452040e1b9fed80

test:
  secret_key_base: acc17674483ce9eefd655f999f63263f7eed34e3e6646bc63d27af415463d5553c3dd876f376aaa8a22efe3f1ea13df78f69a0a7b807ccc5c37cf971f8e4a2fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
